baseURL = "https://denydefydecry.com"
languageCode = "en-us"
title = "TwelfthGhast's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "TwelfthGhast"
  description = "???!!!"
  email = "twelfthghast@gmail.com"
  url = "https://denydefydecry.com"
  lastmod = true
  userStatusEmoji = "👀"
  favicon = "/images/github.png"
  avatar = "/images/avatar.jpg"
  headerIcon = "/images/github-mark-white.png"
  location = "Sydney, Australia"
  enableGitalk = true